# Generated by Django 3.0.5 on 2020-05-03 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_state', models.CharField(choices=[('ONGOING', 'ONGOING'), ('COMPLETE', 'COMPLETE')], default='ONGOING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('games_won', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('state', models.CharField(choices=[('EMPTY', 'EMPTY'), ('OCCUPIED', 'OCCUPIED')], default='EMPTY', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_player', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='game.Player'),
        ),
    ]
